# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Update request state

PUT {{HostAddress}}/api/v1/request/update-state/ec521f88-7b0b-41ed-87e5-e23475649adc
Content-Type: application/json

{
  "newState": 1
}